In [1]:
import pandas as pd
import os
import numpy as np
import re

In [2]:
pd.set_option('display.max_columns', None)

# Data curation

##### 1. Combine dicomtocsv_series.csv and dicomtocsv_study.csv
##### 2. Group by PatientID

### <span style="color:darkcyan">**Function**</span>

In [3]:
def merge_and_extract(file_path, file_series, file_study, output_file, extract_cols):
    """
    Merges two files into a single file based on shared columns, then extract desired columns
    """
    
    df_dicom_series = pd.read_csv(os.path.join(file_path, file_series))
    df_dicom_study = pd.read_csv(os.path.join(file_path, file_study))
    
    series_cols = df_dicom_series.columns
    study_cols = df_dicom_study.columns
    
    common_cols = series_cols.intersection(study_cols)
    series_not_study = series_cols.difference(study_cols)
    study_not_series = study_cols.difference(series_cols)
    
    df_all = pd.merge(df_dicom_series, df_dicom_study, how="outer", on=common_cols.to_list())
    df = df_all[extract_cols]
    
    if output_file:
        df.to_excel(output_file, index=False)
    
    return df_all, df, df_dicom_series, df_dicom_study

In [4]:
def group_by_patient(df, output_file):
    """
    Group dataframe by patient ID
    """    
    PIDs = df["PatientID"].unique()
    num_patient = PIDs.size
    
    count = 0
    for pid in PIDs:
        if count == 0: 
            tmp = df[df["PatientID"] == pid]
        else: 
            tmp = pd.concat([tmp, df[df["PatientID"] == pid]], ignore_index=True)
        count += 1
    
#     tmp.sort_values(by=['PatientID', 'StudyDate'], inplace=True, ignore_index=True)
    tmp.sort_values(by=['PatientID', 'StudyDate', 'AccessionNumber'], inplace=True, ignore_index=True)
    
    if output_file:
        tmp.to_excel(output_file, index=False)
    
    return num_patient, tmp

In [5]:
def calculate_age_at_study(df, output_file):
    """
    Calculates the patient's age in years at the time of the study 
    based on the 'PatientBirthDate' and 'StudyDate' columns.
    """
    
    # 1. Ensure date columns are in datetime format
    # The format 'YYYY-MM-DD' is used for parsing
    try:
        df['BIRTH_DATE_DT'] = pd.to_datetime(df['BIRTH_DATE'], format='%Y-%m-%d')
        # Note: The StudyDate column often includes time (e.g., '2020-06-01 09:10:52').
        # We can let pandas infer the format for this one since it's cleaner.
        df['StudyDate_DT'] = pd.to_datetime(df['StudyDate'], errors='coerce') 
    except ValueError as e:
        print(f"Error parsing date format: {e}. Please check your date column formats.")
        return df

    # 2. Calculate the difference in days
    time_difference = df['StudyDate_DT'] - df['BIRTH_DATE_DT']
    
    # 3. Convert the difference into whole years (integer format)
    # The .dt.days attribute gives the number of days, which is divided by 365.25 
    # and then explicitly cast to an integer to capture only the full years elapsed.
    df['PatientAge'] = (time_difference.dt.days / 365.25).astype(int)
    
    # Clean up the intermediate columns
    df = df.drop(columns=['BIRTH_DATE_DT', 'StudyDate_DT'])

    if output_file:
        df.to_excel(output_file, index=False)
    
    return df

### <span style="color:blue">**Main**</span>

In [6]:
file_path = "../Data/R3Data"

file_series = "dicomtocsv_series.csv"
file_study = "dicomtocsv_study.csv"
# output_file = "../Data/output.xlsx"

extract_cols = ['PatientID', 'AccessionNumber', 'PatientBirthDate', 'PatientAge', 'PatientSex',
        'StudyDate', 'StudyTime', 'AcquisitionDate',
        'StudyDescription', 'SeriesNumber', 'SeriesDescription',
        'Exposure',
        'Rows', 'Columns', 'PixelSpacing',
        'Modality', 'Manufacturer', 'ManufacturerModelName']

df_all, df, df_dicom_series, df_dicom_study = merge_and_extract(file_path, file_series, file_study, None, extract_cols)

In [7]:
df[df['PatientID']==4335033113]

,PatientID,AccessionNumber,PatientBirthDate,PatientAge,PatientSex,StudyDate,StudyTime,AcquisitionDate,StudyDescription,SeriesNumber,SeriesDescription,Exposure,Rows,Columns,PixelSpacing,Modality,Manufacturer,ManufacturerModelName
126285,4335033113,60229362,1959-07-01,NaN,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,L MLO Intelligent 2D,80.0,4096.0,3328.0,0.063901\0.063901,MG,"HOLOGIC, Inc.",Selenia Dimensions
126286,4335033113,60229362,1959-07-01,NaN,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R MLO Intelligent 2D,74.0,4096.0,3328.0,0.064002\0.064002,MG,"HOLOGIC, Inc.",Selenia Dimensions
126287,4335033113,60229362,1959-07-01,NaN,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R MLO Intelligent 2D,77.0,4096.0,3328.0,0.063901\0.063901,MG,"HOLOGIC, Inc.",Selenia Dimensions
126288,4335033113,60229362,1959-07-01,NaN,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R CC Intelligent 2D,65.0,4096.0,3328.0,0.064302\0.064302,MG,"HOLOGIC, Inc.",Selenia Dimensions
126289,4335033113,60229362,1959-07-01,NaN,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,L CC Intelligent 2D,61.0,4096.0,3328.0,0.064503\0.064503,MG,"HOLOGIC, Inc.",Selenia Dimensions
126290,4335033113,60229362,1959-07-01,060Y,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova
134093,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:57,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView
134094,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView
134095,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.107582\0.107582,MG,"HOLOGIC, Inc.",SecurView
134096,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,2021-06-28,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView
134097,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,2021-06-28,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106241\0.106241,MG,"HOLOGIC, Inc.",SecurView
134098,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106241\0.106241,MG,"HOLOGIC, Inc.",SecurView
134099,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,L MLO Intelligent 2D,71.0,4096.0,3328.0,0.064105\0.064105,MG,"HOLOGIC, Inc.",Selenia Dimensions
134100,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R MLO Intelligent 2D,82.0,4096.0,3328.0,0.063703\0.063703,MG,"HOLOGIC, Inc.",Selenia Dimensions
134101,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R CC Intelligent 2D,77.0,4096.0,3328.0,0.064105\0.064105,MG,"HOLOGIC, Inc.",Selenia Dimensions
134102,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R CC Intelligent 2D,61.0,4096.0,3328.0,0.064507\0.064507,MG,"HOLOGIC, Inc.",Selenia Dimensions
134103,4335033113,66697309,1959-07-01,NaN,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,L CC Intelligent 2D,66.0,4096.0,3328.0,0.064507\0.064507,MG,"HOLOGIC, Inc.",Selenia Dimensions
134104,4335033113,66697309,1959-07-01,061Y,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova

In [8]:
output_file = "../Data/dicom.xlsx"
num_patient, output = group_by_patient(df, output_file)

In [9]:
output.rename(columns={'PatientID': 'PATIENT_STUDY_ID', 'AccessionNumber': 'ACCESSION_NUMBER', 'PatientBirthDate': 'BIRTH_DATE'}, inplace=True)

In [10]:
output_file = "../Data/dicom.xlsx"
output_calc_age = calculate_age_at_study(output, output_file)

In [13]:
output_calc_age[output_calc_age['PATIENT_STUDY_ID']==4335033113]

,PATIENT_STUDY_ID,ACCESSION_NUMBER,BIRTH_DATE,PatientAge,PatientSex,StudyDate,StudyTime,AcquisitionDate,StudyDescription,SeriesNumber,SeriesDescription,Exposure,Rows,Columns,PixelSpacing,Modality,Manufacturer,ManufacturerModelName
120554,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,L MLO Intelligent 2D,80.0,4096.0,3328.0,0.063901\0.063901,MG,"HOLOGIC, Inc.",Selenia Dimensions
120555,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R MLO Intelligent 2D,74.0,4096.0,3328.0,0.064002\0.064002,MG,"HOLOGIC, Inc.",Selenia Dimensions
120556,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R MLO Intelligent 2D,77.0,4096.0,3328.0,0.063901\0.063901,MG,"HOLOGIC, Inc.",Selenia Dimensions
120557,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R CC Intelligent 2D,65.0,4096.0,3328.0,0.064302\0.064302,MG,"HOLOGIC, Inc.",Selenia Dimensions
120558,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,L CC Intelligent 2D,61.0,4096.0,3328.0,0.064503\0.064503,MG,"HOLOGIC, Inc.",Selenia Dimensions
120559,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova
120560,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:57,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView
120561,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView
120562,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.107582\0.107582,MG,"HOLOGIC, Inc.",SecurView
120563,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-28,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView
120564,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-28,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106241\0.106241,MG,"HOLOGIC, Inc.",SecurView
120565,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106241\0.106241,MG,"HOLOGIC, Inc.",SecurView
120566,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,L MLO Intelligent 2D,71.0,4096.0,3328.0,0.064105\0.064105,MG,"HOLOGIC, Inc.",Selenia Dimensions
120567,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R MLO Intelligent 2D,82.0,4096.0,3328.0,0.063703\0.063703,MG,"HOLOGIC, Inc.",Selenia Dimensions
120568,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R CC Intelligent 2D,77.0,4096.0,3328.0,0.064105\0.064105,MG,"HOLOGIC, Inc.",Selenia Dimensions
120569,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R CC Intelligent 2D,61.0,4096.0,3328.0,0.064507\0.064507,MG,"HOLOGIC, Inc.",Selenia Dimensions
120570,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,L CC Intelligent 2D,66.0,4096.0,3328.0,0.064507\0.064507,MG,"HOLOGIC, Inc.",Selenia Dimensions
120571,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova

# **Add tags** (Study, Side, Series)

### <span style="color:#FF6347;">**READ**</span> file

In [14]:
file_path = "../Data/dicom.xlsx"
dicom = pd.read_excel(file_path)

In [15]:
dicom

,PATIENT_STUDY_ID,ACCESSION_NUMBER,BIRTH_DATE,PatientAge,PatientSex,StudyDate,StudyTime,AcquisitionDate,StudyDescription,SeriesNumber,SeriesDescription,Exposure,Rows,Columns,PixelSpacing,Modality,Manufacturer,ManufacturerModelName
0,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,74100000.0,SecurView Secondary Capture,NaN,2456.0,1889.0,0.0869174\0.0869174,MG,"HOLOGIC, Inc.",SecurView
1,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,74100000.0,SecurView Secondary Capture,NaN,2456.0,1889.0,0.0526965\0.0526965,MG,"HOLOGIC, Inc.",SecurView
2,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,71100000.0,R ML,102.0,3328.0,2560.0,0.038889\0.038889,MG,"HOLOGIC, Inc.",Selenia Dimensions
3,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,71100000.0,R XCCL,94.0,3328.0,2560.0,0.038889\0.038889,MG,"HOLOGIC, Inc.",Selenia Dimensions
4,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,71300000.0,L XCCL C-View,85.0,2457.0,1890.0,0.086744\0.086744,MG,"HOLOGIC, Inc.",Selenia Dimensions
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136228,4339959661,62216536,1971-07-01,48,F,2019-10-28,02:45:37,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova
136229,4339959661,62216536,1971-07-01,48,F,2019-10-28,02:45:37,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise
136230,4339959661,62216536,1971-07-01,48,F,2019-10-28,02:45:37,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise
136231,4339959661,62216536,1971-07-01,48,F,2019-10-28,18:20:08,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise
136232,4339959661,62216536,1971-07-01,48,F,2019-10-28,18:20:08,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise

In [17]:
dicom["Modality"].unique()

array(['MG', 'PR', 'SR', 'US', 'MR', 'OT', 'KO', 'SC'], dtype=object)

In [18]:
laterality_bi = ["BILATERAL", "BILAT", "BIL", "BI"]
laterality_uni = ["UNILATERAL", "UNILAT", "UNI", "Unilateral"]
other = ["IMPLANT", "CONTRAST ENHANCED", "Implant"]

In [19]:
dicom_copy = dicom.copy()

### <span style="color:blue"> **Study**</span> (SCREEN, DIAG)

In [20]:
study_screen = ["SCREENING", "SCREEN", "Screening"]
study_diag = ["DIAG", "DIAGNOSTIC", "DX", "Diagnostic"]

In [21]:
# Assuming your DataFrame is named 'df' and the column where you found the words is 'Notes'
column_to_check = 'StudyDescription' 
type_column = 'study'

# Ensure the column is treated as strings and handle missing values
dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

# ---Create the OR-Condition Mask ---
# The pattern uses the '|' (OR) symbol.
# We use .str.contains() with case=False to handle both "DIAG" and "Diagnostic".
diag_terms = [term for term in study_diag]
diag_pattern = '|'.join([re.escape(term) for term in diag_terms])

screen_terms = [term for term in study_screen]
screen_pattern = '|'.join([re.escape(term) for term in screen_terms])

# Create a boolean mask: True if the string contains either word (case-insensitive)
diag_mask = dicom_copy[column_to_check].str.contains(diag_pattern, case=False, na=False, regex=True)
screen_mask = dicom_copy[column_to_check].str.contains(screen_pattern, case=False, na=False, regex=True)

# --- Assign the value "DIAG" to the 'type' column ---
# Use .loc to assign the value only where the mask is True
dicom_copy.loc[diag_mask, type_column] = "DIAG"
dicom_copy.loc[screen_mask, type_column] = "SCREEN"

### <span style="color:blue">**Side**</span> (R, L)

In [22]:
side_right = ["RIGHT", "RT", "Right", "R XCCL", "R MLO", "R CC", "R ML", "R SIO", "R LM"]
side_left = ["LEFT", "LT", "Left", "L XCCL", "L MLO", "L CC", "L ML", "L SIO", "L LM"]

In [23]:
# Assuming your DataFrame is named 'df' and the column where you found the words is 'Notes'
column_to_check = 'SeriesDescription' 
type_column = 'side'

# Ensure the column is treated as strings and handle missing values
dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

# ---Create the OR-Condition Mask ---
# The pattern uses the '|' (OR) symbol.
# We use .str.contains() with case=False to handle both "DIAG" and "Diagnostic".
side_right_terms = [term for term in side_right]
side_right_pattern = '|'.join([re.escape(term) for term in side_right_terms])

side_left_terms = [term for term in side_left]
side_left_pattern = '|'.join([re.escape(term) for term in side_left_terms])

# Create a boolean mask: True if the string contains either word (case-insensitive)
side_right_mask = dicom_copy[column_to_check].str.contains(side_right_pattern, case=False, na=False, regex=True)
side_left_mask = dicom_copy[column_to_check].str.contains(side_left_pattern, case=False, na=False, regex=True)


# --- Assign the value "DIAG" to the 'type' column ---
# Use .loc to assign the value only where the mask is True
dicom_copy.loc[side_right_mask, type_column] = "R"
dicom_copy.loc[side_left_mask, type_column] = "L"

### <span style="color:blue">**Series**</span> (DBT, IN2D, C VIEW, SECURE)

In [24]:
series_dbt = ["TOMOSYNTHESIS", "TOMOSYN", "TOMO", "TOMOHD", "TomoHD", "Tomosynthesis"]
series_in2d = ["Intelligent 2D"]
series_cview = ["C-View"]
series_secure = ["SecurView"]

In [25]:
# Assuming your DataFrame is named 'df' and the column where you found the words is 'Notes'
column_to_check = 'SeriesDescription' 
type_column = 'series'

# Ensure the column is treated as strings and handle missing values
dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

# ---Create the OR-Condition Mask ---
# The pattern uses the '|' (OR) symbol.
dbt_terms = [term for term in series_dbt]
dbt_pattern = '|'.join([re.escape(term) for term in dbt_terms])

in2d_terms = [term for term in series_in2d]
in2d_pattern = '|'.join([re.escape(term) for term in in2d_terms])

cview_terms = [term for term in series_cview]
cview_pattern = '|'.join([re.escape(term) for term in cview_terms])

secure_terms = [term for term in series_secure]
secure_pattern = '|'.join([re.escape(term) for term in secure_terms])

# Create a boolean mask: True if the string contains either word (case-insensitive)
dbt_mask = dicom_copy[column_to_check].str.contains(dbt_pattern, case=False, na=False, regex=True)
in2d_mask = dicom_copy[column_to_check].str.contains(in2d_pattern, case=False, na=False, regex=True)
cview_mask = dicom_copy[column_to_check].str.contains(cview_pattern, case=False, na=False, regex=True)
secure_mask = dicom_copy[column_to_check].str.contains(secure_pattern, case=False, na=False, regex=True)

# --- Assign the value "DBT" to the 'type' column ---
# Use .loc to assign the value only where the mask is True
dicom_copy.loc[dbt_mask, type_column] = "DBT"
dicom_copy.loc[in2d_mask, type_column] = "IN2D"
dicom_copy.loc[cview_mask, type_column] = "C VIEW"
dicom_copy.loc[secure_mask, type_column] = "SECURE"

In [26]:
dicom_copy

,PATIENT_STUDY_ID,ACCESSION_NUMBER,BIRTH_DATE,PatientAge,PatientSex,StudyDate,StudyTime,AcquisitionDate,StudyDescription,SeriesNumber,SeriesDescription,Exposure,Rows,Columns,PixelSpacing,Modality,Manufacturer,ManufacturerModelName,study,side,series
0,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,74100000.0,SecurView Secondary Capture,NaN,2456.0,1889.0,0.0869174\0.0869174,MG,"HOLOGIC, Inc.",SecurView,DIAG,NaN,SECURE
1,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,74100000.0,SecurView Secondary Capture,NaN,2456.0,1889.0,0.0526965\0.0526965,MG,"HOLOGIC, Inc.",SecurView,DIAG,NaN,SECURE
2,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,71100000.0,R ML,102.0,3328.0,2560.0,0.038889\0.038889,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG,R,NaN
3,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,71100000.0,R XCCL,94.0,3328.0,2560.0,0.038889\0.038889,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG,R,NaN
4,4330018595,63737104,1965-07-01,54,F,2019-08-19,02:11:20,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,71300000.0,L XCCL C-View,85.0,2457.0,1890.0,0.086744\0.086744,MG,"HOLOGIC, Inc.",Selenia Dimensions,DIAG,L,C VIEW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
136228,4339959661,62216536,1971-07-01,48,F,2019-10-28,02:45:37,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova,SCREEN,NaN,NaN
136229,4339959661,62216536,1971-07-01,48,F,2019-10-28,02:45:37,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREEN,NaN,NaN
136230,4339959661,62216536,1971-07-01,48,F,2019-10-28,02:45:37,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREEN,NaN,NaN
136231,4339959661,62216536,1971-07-01,48,F,2019-10-28,18:20:08,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREEN,NaN,NaN
136232,4339959661,62216536,1971-07-01,48,F,2019-10-28,18:20:08,NaN,SCREENING MAMMOGRAPHY DIGITAL BILATERAL W TOMOSYN,1.0,5DBAD14E0,NaN,NaN,NaN,NaN,PR,Philips Medical Systems,iSite Enterprise,SCREEN,NaN,NaN

### <span style="color:blue">**View**</span> (MLO, CC)

In [27]:
view_mlo = ["L MLO", "R MLO"]
view_cc = ["L CC", "R CC"]

In [28]:
# Assuming your DataFrame is named 'df' and the column where you found the words is 'Notes'
column_to_check = 'SeriesDescription' 
type_column = 'view'

# Ensure the column is treated as strings and handle missing values
dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

# ---Create the OR-Condition Mask ---
# The pattern uses the '|' (OR) symbol.
view_mlo_terms = [term for term in view_mlo]
view_mlo_pattern = '|'.join([re.escape(term) for term in view_mlo_terms])

view_cc_terms = [term for term in view_cc]
view_cc_pattern = '|'.join([re.escape(term) for term in view_cc_terms])

# Create a boolean mask: True if the string contains either word (case-insensitive)
view_mlo_mask = dicom_copy[column_to_check].str.contains(view_mlo_pattern, case=False, na=False, regex=True)
view_cc_mask = dicom_copy[column_to_check].str.contains(view_cc_pattern, case=False, na=False, regex=True)


# --- Assign the value "DIAG" to the 'type' column ---
# Use .loc to assign the value only where the mask is True
dicom_copy.loc[view_mlo_mask, type_column] = "MLO"
dicom_copy.loc[view_cc_mask, type_column] = "CC"

### <span style="color:#FF6347;">**SAVE**</span> file

In [29]:
output_file = os.path.join("../Data/",'dicom_tag' + ".xlsx")
dicom_copy.to_excel(output_file, index=False)

### <span style="color:#FF6347;">**READ**</span> file

In [30]:
file_path = os.path.join("../Data/",'dicom_tag' + ".xlsx")
dicom = pd.read_excel(file_path)

In [32]:
dicom[dicom["series"]=="DBT"]["PATIENT_STUDY_ID"].unique().size

759

In [33]:
dicom[dicom['PATIENT_STUDY_ID']==4335033113]

,PATIENT_STUDY_ID,ACCESSION_NUMBER,BIRTH_DATE,PatientAge,PatientSex,StudyDate,StudyTime,AcquisitionDate,StudyDescription,SeriesNumber,SeriesDescription,Exposure,Rows,Columns,PixelSpacing,Modality,Manufacturer,ManufacturerModelName,study,side,series,view
120554,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,L MLO Intelligent 2D,80.0,4096.0,3328.0,0.063901\0.063901,MG,"HOLOGIC, Inc.",Selenia Dimensions,NaN,L,IN2D,MLO
120555,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R MLO Intelligent 2D,74.0,4096.0,3328.0,0.064002\0.064002,MG,"HOLOGIC, Inc.",Selenia Dimensions,NaN,R,IN2D,MLO
120556,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R MLO Intelligent 2D,77.0,4096.0,3328.0,0.063901\0.063901,MG,"HOLOGIC, Inc.",Selenia Dimensions,NaN,R,IN2D,MLO
120557,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,R CC Intelligent 2D,65.0,4096.0,3328.0,0.064302\0.064302,MG,"HOLOGIC, Inc.",Selenia Dimensions,NaN,R,IN2D,CC
120558,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,71300000.0,L CC Intelligent 2D,61.0,4096.0,3328.0,0.064503\0.064503,MG,"HOLOGIC, Inc.",Selenia Dimensions,NaN,L,IN2D,CC
120559,4335033113,60229362,1959-07-01,60,F,2020-03-13,11:57:21,NaN,MAMMOGRAM DIGITAL SCR BILAT,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova,NaN,NaN,NaN,NaN
120560,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:57,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView,SCREEN,NaN,SECURE,NaN
120561,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView,SCREEN,NaN,SECURE,NaN
120562,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.107582\0.107582,MG,"HOLOGIC, Inc.",SecurView,SCREEN,NaN,SECURE,NaN
120563,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-28,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106911\0.106911,MG,"HOLOGIC, Inc.",SecurView,SCREEN,NaN,SECURE,NaN
120564,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-28,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106241\0.106241,MG,"HOLOGIC, Inc.",SecurView,SCREEN,NaN,SECURE,NaN
120565,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,2021-06-06,SCREENING MAMMO WITH TOMO,74100000.0,SecurView Secondary Capture,NaN,2456.0,1995.0,0.106241\0.106241,MG,"HOLOGIC, Inc.",SecurView,SCREEN,NaN,SECURE,NaN
120566,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,L MLO Intelligent 2D,71.0,4096.0,3328.0,0.064105\0.064105,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREEN,L,IN2D,MLO
120567,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R MLO Intelligent 2D,82.0,4096.0,3328.0,0.063703\0.063703,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREEN,R,IN2D,MLO
120568,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R CC Intelligent 2D,77.0,4096.0,3328.0,0.064105\0.064105,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREEN,R,IN2D,CC
120569,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,R CC Intelligent 2D,61.0,4096.0,3328.0,0.064507\0.064507,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREEN,R,IN2D,CC
120570,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,71300000.0,L CC Intelligent 2D,66.0,4096.0,3328.0,0.064507\0.064507,MG,"HOLOGIC, Inc.",Selenia Dimensions,SCREEN,L,IN2D,CC
120571,4335033113,66697309,1959-07-01,61,F,2021-05-29,11:53:58,NaN,SCREENING MAMMO WITH TOMO,1.0,Hologic R2 ImageChecker CAD SC,NaN,1500.0,1250.0,NaN,MG,"R2 Technology, Inc.",Cenova,SCREEN,NaN,NaN,NaN