In [1]:
import pandas as pd
import os
import numpy as np
import re

In [2]:
pd.set_option('display.max_columns', None)

# <span style="color:blue;">**Cancer**</span>

In [3]:
study = "Cancer"

## **STEP 0: Data preparation**

### 1. DICOM

#### Visit [parameter exlanation][peid] for more information

[peid]: https://pitt-my.sharepoint.com/:w:/r/personal/trl117_pitt_edu/_layouts/15/Doc.aspx?sourcedoc=%7B7B05A758-0D43-40AF-9177-E9C7522D2649%7D&file=Notes_parameters%20explaination.docx&action=default&mobileredirect=true

In [4]:
# file_path = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/dicom_tag.xlsx"
file_path = "/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data/dicom_tag.xlsx"
dicom = pd.read_excel(file_path)

In [5]:
dicom.rename(columns={'PatientID': 'PATIENT_STUDY_ID', 'AccessionNumber': 'ACCESSION_NUMBER'}, inplace=True)

In [6]:
dicom["PATIENT_STUDY_ID"].unique().size

5864

In [7]:
PIDs = dicom["PATIENT_STUDY_ID"].unique()

In [8]:
dicom.head(5)

,PATIENT_STUDY_ID,PatientBirthDate,PatientAge,ACCESSION_NUMBER,StudyDate,Study,Side,Series,View,Slab,StudyDescription,SeriesDescription,SeriesNumber,Manufacturer,ManufacturerModelName,SliceThickness,Exposure,Rows,Columns,PixelSpacing,FolderPath
0,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,NaN,SECURE,NaN,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,Hologic R2 ImageChecker CAD SC,1,"R2 Technology, Inc.",Cenova,NaN,NaN,1500.0,1250.0,NaN,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
1,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,R,FFDM,ML,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R ML,71100000,"HOLOGIC, Inc.",Selenia Dimensions,NaN,102.0,3328.0,2560.0,0.038889\0.038889,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
2,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,R,FFDM,XCCL,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R XCCL,71100000,"HOLOGIC, Inc.",Selenia Dimensions,NaN,94.0,3328.0,2560.0,0.038889\0.038889,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
3,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,L,C VIEW,LM,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,L LM C-View,71300000,"HOLOGIC, Inc.",Selenia Dimensions,NaN,71.0,2457.0,1890.0,0.087290\0.087290,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
4,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,L,C VIEW,MLO,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,L MLO C-View,71300000,"HOLOGIC, Inc.",Selenia Dimensions,NaN,87.0,2457.0,1890.0,0.086609\0.086609,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...

#### Create a list of unique study visit to serve as the reference linking the EHR to the images available for specific patient visits (as images are limited to certain visits, not all).

#### See shared parameters in [parameter exlanation][peid] to link data

[peid]: https://pitt-my.sharepoint.com/:w:/r/personal/trl117_pitt_edu/_layouts/15/Doc.aspx?sourcedoc=%7B7B05A758-0D43-40AF-9177-E9C7522D2649%7D&file=Notes_parameters%20explaination.docx&action=default&mobileredirect=true

In [9]:
# Define the key identifier columns and columns to extract
key_columns = ['PATIENT_STUDY_ID', 'PatientAge', 'ACCESSION_NUMBER', 'StudyDate', 'Study', 'Side', 'Slab']
unique_study = dicom.drop_duplicates(subset=key_columns, keep='first')

unique_study = unique_study[key_columns]
unique_study = unique_study[unique_study['Side'].notna()]

unique_study.reset_index(drop=True, inplace=True)

In [10]:
unique_study.head(5)

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,Side,Slab
0,4330018595,54.0,63737104,2019-08-19,DIAG,R,NaN
1,4330018595,54.0,63737104,2019-08-19,DIAG,L,NaN
2,4330018595,54.0,60103700,2020-06-02,DIAG,R,NaN
3,4330018595,54.0,60690108,2020-06-02,SCREEN,L,NaN
4,4330018595,56.0,452973800,2022-06-09,SCREEN,L,Y

In [11]:
unique_study["PATIENT_STUDY_ID"].nunique()

5860

#### Filter study with DBT

In [12]:
dicom_dbt = dicom[dicom["Series"]=="DBT"]

key_columns = ['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'StudyDate', 'Study', 'Side', 'Slab']
unique_study_dicom_dbt = dicom_dbt.drop_duplicates(subset=key_columns, keep='first')
unique_study_dicom_dbt.reset_index(drop=True, inplace=True)

In [13]:
unique_study_dicom_dbt.head(5)

,PATIENT_STUDY_ID,PatientBirthDate,PatientAge,ACCESSION_NUMBER,StudyDate,Study,Side,Series,View,Slab,StudyDescription,SeriesDescription,SeriesNumber,Manufacturer,ManufacturerModelName,SliceThickness,Exposure,Rows,Columns,PixelSpacing,FolderPath
0,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,L,DBT,LM,NaN,BREAST IMAGING TOMOSYNTHESIS,L LM Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1890.0,0.087290\0.087290,J:\Testing\jlee\MO_DBT\1.63TB_Tomos_Round_13\P...
1,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,R,DBT,XCCL,NaN,BREAST IMAGING TOMOSYNTHESIS,R XCCL Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1890.0,0.087018\0.087018,J:\Testing\jlee\MO_DBT\1.63TB_Tomos_Round_13\P...
2,4330018595,1965-07-01,54.0,60103700,2020-06-02,DIAG,R,DBT,CC,NaN,DIAGNOSTIC RIGHT UNILATERAL WITH TOMO,R CC Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,3328.0,2560.0,0.064519\0.064519,J:\Testing\jlee\MO_DBT\1.63TB_Tomos_Round_13\P...
3,4330018595,1965-07-01,54.0,60690108,2020-06-02,SCREEN,L,DBT,CC,NaN,SCREENING MAMMOGRAM WITH TOMO,L CC Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,3328.0,2560.0,0.064418\0.064418,J:\Testing\jlee\MO_DBT\1.63TB_Tomos_Round_13\P...
4,4330018595,1965-07-01,56.0,452973800,2022-06-09,SCREEN,L,DBT,CC,Y,SCREENING MAMMOGRAM WITH TOMO,L CC Breast Tomosynthesis Image Slabs,73500000,"HOLOGIC, Inc.",Selenia Dimensions,6.0,NaN,3328.0,2560.0,0.063615\0.063615,J:\Testing\jlee\MO_DBT\1.21TB_Tomos_Round_12\P...

In [14]:
unique_study_dicom_dbt["PATIENT_STUDY_ID"].nunique()

5140

In [15]:
unique_patient_dbt = unique_study[unique_study["PATIENT_STUDY_ID"].isin(unique_study_dicom_dbt["PATIENT_STUDY_ID"].unique())]

In [16]:
unique_patient_dbt # unique patient that has dbt across stidues

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,Side,Slab
0,4330018595,54.0,63737104,2019-08-19,DIAG,R,NaN
1,4330018595,54.0,63737104,2019-08-19,DIAG,L,NaN
2,4330018595,54.0,60103700,2020-06-02,DIAG,R,NaN
3,4330018595,54.0,60690108,2020-06-02,SCREEN,L,NaN
4,4330018595,56.0,452973800,2022-06-09,SCREEN,L,Y
...,...,...,...,...,...,...,...
38162,4339945522,45.0,62906727,2019-10-18,DIAG,R,NaN
38163,4339945522,48.0,450264459,2022-10-14,DIAG,L,NaN
38164,4339945522,48.0,450264459,2022-10-14,DIAG,R,NaN
38165,4339945522,48.0,450264459,2022-10-14,DIAG,L,Y
38166,4339945522,48.0,450264459,2022-10-14,DIAG,R,Y

In [17]:
unique_patient_dbt = pd.merge(
    unique_patient_dbt,
    unique_study_dicom_dbt[['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'StudyDate', 'Study', 'Side', 'Series', 'Slab']],
    on = key_columns,
    how='left'
)

In [18]:
unique_patient_dbt

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,Side,Slab,Series
0,4330018595,54.0,63737104,2019-08-19,DIAG,R,NaN,DBT
1,4330018595,54.0,63737104,2019-08-19,DIAG,L,NaN,DBT
2,4330018595,54.0,60103700,2020-06-02,DIAG,R,NaN,DBT
3,4330018595,54.0,60690108,2020-06-02,SCREEN,L,NaN,DBT
4,4330018595,56.0,452973800,2022-06-09,SCREEN,L,Y,DBT
...,...,...,...,...,...,...,...,...
35688,4339945522,45.0,62906727,2019-10-18,DIAG,R,NaN,DBT
35689,4339945522,48.0,450264459,2022-10-14,DIAG,L,NaN,NaN
35690,4339945522,48.0,450264459,2022-10-14,DIAG,R,NaN,NaN
35691,4339945522,48.0,450264459,2022-10-14,DIAG,L,Y,DBT
35692,4339945522,48.0,450264459,2022-10-14,DIAG,R,Y,DBT

### 2. Electric Health Record

#### Visit [parameter exlanation][peid] for more information

[peid]: https://pitt-my.sharepoint.com/:w:/r/personal/trl117_pitt_edu/_layouts/15/Doc.aspx?sourcedoc=%7B7B05A758-0D43-40AF-9177-E9C7522D2649%7D&file=Notes_parameters%20explaination.docx&action=default&mobileredirect=true

In [19]:
# file_path = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/parameters of interest.xlsx"
file_path = "/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data/parameters of interest.xlsx"
file_name = pd.ExcelFile(file_path).sheet_names
file_name

['enteredit_findings',
 'pathology',
 'pathology_findings',
 'patient_data_ie',
 'hormonal_mens',
 'risk_factors',
 'vitals',
 'patient_demo',
 'procedure_notes',
 'procedures']

---

# **Extract <span style="color:blue;">MO Cancer**</span>

#### See [inclusion criteria][ic] to for filtering

[ic]: https://pitt-my.sharepoint.com/:w:/r/personal/trl117_pitt_edu/_layouts/15/doc.aspx?sourcedoc=%7B9c403413-a771-4830-98ab-15171872c4dd%7D&action=edit

## **STEP 1**. Merge enteredit_findings with pathology, then merge with patient with DBT available
### (OUTPUT) cancer_cohort

enteredit_findings
* Columns: COMPOSITION_NAME, FINDING_LOCATION, FINDING_CATEGORY, FINDING_REC, EXAM_COMPLETED_DATE
* Cancer: 
    * FINDING_CATEGORY = 4, 4A, 4B, 4C, 5

pathology
* Columns: BX_ID, PATHOLOGY_DATE, LESION_CLASS, SIDE
* Cancer: 
    * LESION_CLASS = 'Malignant'

In [20]:
file_name

['enteredit_findings',
 'pathology',
 'pathology_findings',
 'patient_data_ie',
 'hormonal_mens',
 'risk_factors',
 'vitals',
 'patient_demo',
 'procedure_notes',
 'procedures']

In [21]:
fn = file_name[0]
# file_path = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, "Cleaned", fn + ".xlsx")
file_path = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, "Cleaned", fn + ".xlsx")
birads = pd.read_excel(file_path)

In [22]:
birads.head(3)

,PATIENT_STUDY_ID,ACCESSION_NUMBER,COMPOSITION_NAME,FINDING_LOCATION,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,duplicate_count
0,4330018595,63027507,Heterogeneously dense (51% - 75%),NaN,0 - Need additional imaging evaluation,P-Additional projections,2019-07-26,2
1,4330018595,63737104,Heterogeneously dense (51% - 75%),NaN,2 - Benign finding,N-Normal interval follow-up,2019-08-19,1
2,4330018595,63737104,Heterogeneously dense (51% - 75%),NaN,3 - Probably benign - short interval follow-up,F-Follow-up at short interval (1-11 months),2019-08-19,1

In [23]:
birads.drop(columns="FINDING_LOCATION", inplace=True)

In [24]:
fn = file_name[1]
# file_path = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, "Cleaned", fn + ".xlsx")
file_path = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, "Cleaned", fn + ".xlsx")
pathology = pd.read_excel(file_path)

In [25]:
pathology.head(3)

   PATIENT_STUDY_ID   BX_ID PATHOLOGY_DATE LESION_CLASS SIDE
0        4330018595  487690     2020-06-05    Malignant    R
1        4330018595  475789     2020-07-28    Malignant    R
2        4330029102  477464     2021-05-10       Benign    R

In [26]:
biopsy_categories = [
    '4 - Suspicious abnormality, biopsy should be considered',
    '4A - Suspicious abnormality - biopsy should be considered - low suspicion',
    '4B - Suspicious abnormality - biopsy should be considered - intermediate suspicion',
    '4C - Suspicious abnormality - biopsy should be considered - moderate suspicion',
    '5 - Highly suggestive of malignancy, appropriate action should be taken'
]

In [27]:
# ── STEP 1: Merge birads + pathology ────────────────────────────────────────

birads['EXAM_COMPLETED_DATE'] = pd.to_datetime(birads['EXAM_COMPLETED_DATE'])
pathology['PATHOLOGY_DATE']   = pd.to_datetime(pathology['PATHOLOGY_DATE'])
birads['needs_biopsy']        = birads['FINDING_CATEGORY'].isin(biopsy_categories)

# STEP 1.1: Biopsy findings → link to pathology via date window
birads_biopsy    = birads[birads['needs_biopsy']].copy()
biopsy_with_path = pd.merge(birads_biopsy, pathology, on='PATIENT_STUDY_ID', how='left')
biopsy_with_path = biopsy_with_path[
    (biopsy_with_path['PATHOLOGY_DATE'] >= biopsy_with_path['EXAM_COMPLETED_DATE']) &
    (biopsy_with_path['PATHOLOGY_DATE'] <= biopsy_with_path['EXAM_COMPLETED_DATE'] + pd.DateOffset(months=6))
]
biopsy_with_path['days_diff'] = (
    biopsy_with_path['PATHOLOGY_DATE'] - biopsy_with_path['EXAM_COMPLETED_DATE']
).dt.days
biopsy_with_path = (
    biopsy_with_path
    .sort_values('days_diff')
    .drop_duplicates(subset=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'SIDE'], keep='first')
    .drop(columns='days_diff')
)

# STEP 1.2: Non-biopsy findings → assign opposite side,
#           but ONLY when exactly one biopsy side exists (L+R = ambiguous → skip)
birads_no_biopsy = birads[~birads['needs_biopsy']].copy()

biopsy_sides = (
    biopsy_with_path[['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'SIDE']]
    .drop_duplicates()
    .rename(columns={'SIDE': 'biopsy_side'})
)
single_side_accessions = (
    biopsy_sides
    .groupby(['PATIENT_STUDY_ID', 'ACCESSION_NUMBER'])
    .filter(lambda g: len(g) == 1)
)

birads_no_biopsy = pd.merge(
    birads_no_biopsy, single_side_accessions,
    on=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER'], how='left'
)
birads_no_biopsy['SIDE'] = birads_no_biopsy['biopsy_side'].map({'L': 'R', 'R': 'L'})
birads_no_biopsy = birads_no_biopsy.drop(columns='biopsy_side')

# STEP 1.3: Rows still without SIDE, accession has NO biopsy at all,
#           and duplicate_count >= 2 → bilateral exam → duplicate as L and R
biopsy_accession_keys = biopsy_sides[['PATIENT_STUDY_ID', 'ACCESSION_NUMBER']].drop_duplicates()

no_side_rows  = birads_no_biopsy[birads_no_biopsy['SIDE'].isna()].copy()
has_side_rows = birads_no_biopsy[birads_no_biopsy['SIDE'].notna()].copy()

no_side_rows = no_side_rows.merge(
    biopsy_accession_keys, on=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER'],
    how='left', indicator=True
)
truly_no_biopsy  = no_side_rows['_merge'] == 'left_only'
no_side_rows     = no_side_rows.drop(columns='_merge')

bilateral_mask = truly_no_biopsy & (no_side_rows['duplicate_count'] >= 2)
bilateral      = no_side_rows[bilateral_mask]
rest           = no_side_rows[~bilateral_mask]

bilateral_L = bilateral.copy(); bilateral_L['SIDE'] = 'L'
bilateral_R = bilateral.copy(); bilateral_R['SIDE'] = 'R'

birads_no_biopsy = pd.concat(
    [has_side_rows, bilateral_L, bilateral_R, rest], ignore_index=True
)

birads_with_path = pd.concat([biopsy_with_path, birads_no_biopsy], ignore_index=True)

In [28]:
# ── STEP 2: Connect to DICOM images (unique_patient_dbt) ─────────────────────

unique_patient_dbt = unique_patient_dbt.rename(columns={'Side': 'SIDE'})

has_side = (birads_with_path[birads_with_path['SIDE'].notna()]
            .drop_duplicates(subset=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'SIDE'], keep='first'))
no_side  = (birads_with_path[birads_with_path['SIDE'].isna()]
            .drop_duplicates(subset=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER'], keep='first')
            .drop(columns='SIDE'))

# 1. Sided match
merge_sided = pd.merge(
    unique_patient_dbt, has_side,
    on=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'SIDE'], how='inner'
)

# 2. No-side match — only DICOM rows whose accession wasn't already matched above
sided_accessions = merge_sided[['PATIENT_STUDY_ID', 'ACCESSION_NUMBER']].drop_duplicates()
dicom_unmatched  = unique_patient_dbt.merge(
    sided_accessions, on=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER'],
    how='left', indicator=True
).query('_merge == "left_only"').drop(columns='_merge')

merge_no_side = pd.merge(
    dicom_unmatched, no_side,
    on=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER'], how='inner'
)

# 3. DICOM rows with no birads match at all → keep with NaN birads columns
matched_keys = pd.concat([
    merge_sided[['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'SIDE']],
    merge_no_side[['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'SIDE']]
]).drop_duplicates()

no_birads = unique_patient_dbt.merge(
    matched_keys, on=['PATIENT_STUDY_ID', 'ACCESSION_NUMBER', 'SIDE'],
    how='left', indicator=True
).query('_merge == "left_only"').drop(columns='_merge')

df_final = pd.concat([merge_sided, merge_no_side, no_birads], ignore_index=True)
df_final = df_final.sort_values(['PATIENT_STUDY_ID', 'StudyDate', 'ACCESSION_NUMBER', 'SIDE'], ignore_index=True).drop(columns=['duplicate_count', 'needs_biopsy'])

print(f"unique_patient_dbt : {unique_patient_dbt.shape[0]} rows")
print(f"  ↳ with side      : {len(merge_sided)}")
print(f"  ↳ without side   : {len(merge_no_side)}")
print(f"  ↳ no birads      : {len(no_birads)}")
print(f"df_final           : {df_final.shape[0]} rows")

unique_patient_dbt : 35693 rows
  ↳ with side      : 25192
  ↳ without side   : 9036
  ↳ no birads      : 1465
df_final           : 35693 rows

In [29]:
df_final.loc[df_final['FINDING_CATEGORY'].isna(), 'PATIENT_STUDY_ID'].nunique()

525

In [30]:
unique_patient_dbt[unique_patient_dbt['PATIENT_STUDY_ID']==4339601084]

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,SIDE,Slab,Series
35611,4339601084,46.0,77038224,2018-11-07,DIAG,L,NaN,DBT
35612,4339601084,46.0,77038224,2018-11-07,DIAG,R,NaN,DBT
35613,4339601084,46.0,65758752,2019-05-16,DIAG,R,NaN,DBT
35614,4339601084,47.0,60049293,2020-04-09,SCREEN,L,NaN,NaN
35615,4339601084,47.0,60049293,2020-04-09,SCREEN,R,NaN,NaN

In [31]:
df_final[df_final['PATIENT_STUDY_ID']==4339601084]

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,SIDE,Slab,Series,COMPOSITION_NAME,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,BX_ID,PATHOLOGY_DATE,LESION_CLASS
35611,4339601084,46.0,77038224,2018-11-07,DIAG,L,NaN,DBT,NaN,NaN,NaN,NaT,NaN,NaT,NaN
35612,4339601084,46.0,77038224,2018-11-07,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),"4 - Suspicious abnormality, biopsy should be c...",B-Biopsy should be considered,2018-11-07,427183.0,2018-11-14,Benign
35613,4339601084,46.0,65758752,2019-05-16,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),1 - Negative,N-Normal interval follow-up,2019-05-16,NaN,NaT,NaN
35614,4339601084,47.0,60049293,2020-04-09,SCREEN,L,NaN,NaN,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-04-09,NaN,NaT,NaN
35615,4339601084,47.0,60049293,2020-04-09,SCREEN,R,NaN,NaN,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-04-09,NaN,NaT,NaN

In [32]:
birads[birads['PATIENT_STUDY_ID']==4339601084]

,PATIENT_STUDY_ID,ACCESSION_NUMBER,COMPOSITION_NAME,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,duplicate_count,needs_biopsy
87049,4339601084,70648957,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2017-10-11,2,False
87050,4339601084,79474989,Heterogeneously dense (51% - 75%),0 - Need additional imaging evaluation,U-Ultrasound,2017-11-07,1,False
87051,4339601084,79474989,Heterogeneously dense (51% - 75%),1 - Negative,N-Normal interval follow-up,2017-11-07,1,False
87052,4339601084,79253799,Heterogeneously dense (51% - 75%),"4 - Suspicious abnormality, biopsy should be c...",B-Biopsy should be considered,2017-11-16,1,True
87053,4339601084,78102132,Heterogeneously dense (51% - 75%),3 - Probably benign - short interval follow-up,F-Follow-up at short interval (1-11 months),2018-05-24,1,False
87054,4339601084,77038224,Heterogeneously dense (51% - 75%),"4 - Suspicious abnormality, biopsy should be c...",B-Biopsy should be considered,2018-11-07,1,True
87055,4339601084,65758752,Heterogeneously dense (51% - 75%),1 - Negative,N-Normal interval follow-up,2019-05-16,1,False
87056,4339601084,60049293,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-04-09,2,False
87057,4339601084,67077961,Scattered fibroglandular (25% - 50%),2 - Benign finding,N-Normal interval follow-up,2021-04-15,2,False
87058,4339601084,452833482,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-04-25,2,False

In [33]:
pathology[pathology['PATIENT_STUDY_ID']==4339601084]

       PATIENT_STUDY_ID   BX_ID PATHOLOGY_DATE LESION_CLASS SIDE
11297        4339601084  436123     2017-11-22       Benign    R
11298        4339601084  436122     2017-11-22       Benign    R
11299        4339601084  436121     2017-11-22       Benign    R
11300        4339601084  427183     2018-11-14       Benign    R

In [34]:
df_step1 = df_final.copy()

In [35]:
df_step1.shape

(35693, 15)

In [36]:
df_step1["EXAM_COMPLETED_DATE"] = df_step1["EXAM_COMPLETED_DATE"].dt.strftime("%Y-%m-%d")
df_step1["PATHOLOGY_DATE"] = df_step1["PATHOLOGY_DATE"].dt.strftime("%Y-%m-%d")

### <span style="color:#FF6347;">**SAVE**</span> file

In [37]:
# output_file = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, 'cancer_cohort' + ".xlsx")
output_file = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, "cancer_cohort" + ".xlsx")
df_step1.to_excel(output_file, index=False)

## **STEP 2**. <span style="color:blue;">**MO cancer**</span>: Label  "Index" = <span style="color:#8A2BE2;">**INDEX**</span> or <span style="color:#00BFFF;">**INDEX-1**</span>
### (OUTPUT) cancer_cohort_index

### <span style="color:#FF6347;">**READ**</span> file (cancer_cohort)

In [38]:
# output_file = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, 'cancer_cohort' + ".xlsx")
output_file = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, "cancer_cohort" + ".xlsx")
cancer_cohort = pd.read_excel(output_file)

In [39]:
cancer_cohort["EXAM_COMPLETED_DATE"] = pd.to_datetime(cancer_cohort["EXAM_COMPLETED_DATE"], format="%Y-%m-%d")
cancer_cohort["PATHOLOGY_DATE"] = pd.to_datetime(cancer_cohort["PATHOLOGY_DATE"], format="%Y-%m-%d")

In [40]:
cancer_cohort["PATIENT_STUDY_ID"].nunique()

5140

In [41]:
cancer_cohort.head(5)

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,SIDE,Slab,Series,COMPOSITION_NAME,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,BX_ID,PATHOLOGY_DATE,LESION_CLASS
0,4330018595,54.0,63737104,2019-08-19,DIAG,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN
1,4330018595,54.0,63737104,2019-08-19,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN
2,4330018595,54.0,60103700,2020-06-02,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),"5 - Highly suggestive of malignancy, appropria...",B-Biopsy should be considered,2020-06-02,487690.0,2020-06-05,Malignant
3,4330018595,54.0,60690108,2020-06-02,SCREEN,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-06-02,NaN,NaT,NaN
4,4330018595,56.0,452973800,2022-06-09,SCREEN,L,Y,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-06-09,NaN,NaT,NaN

## 1. Locate <span style="color:blue;">**Cancer**</span> year, "Index" = <span style="color:#8A2BE2;">**INDEX**</span>

#### See [inclusion criteria][ic] to for filtering

[ic]: https://pitt-my.sharepoint.com/:w:/r/personal/trl117_pitt_edu/_layouts/15/doc.aspx?sourcedoc=%7B9c403413-a771-4830-98ab-15171872c4dd%7D&action=edit

In [42]:
# ── Find earliest Malignant pathology per patient → INDEX date ───────────────

cohort = cancer_cohort.copy()
cohort['Index'] = None

# 1. Find the earliest Malignant PATHOLOGY_DATE per patient
first_malignant = (
    cohort[cohort['LESION_CLASS'] == 'Malignant']
    .sort_values('PATHOLOGY_DATE')
    .drop_duplicates(subset=['PATIENT_STUDY_ID'], keep='first')
    [['PATIENT_STUDY_ID', 'PATHOLOGY_DATE']]
    .rename(columns={'PATHOLOGY_DATE': 'target pathology date'})
)

cohort = cohort.merge(first_malignant, on='PATIENT_STUDY_ID', how='left')

# 2. Mark exams within 6 months BEFORE (or on) the index pathology date
six_months = pd.Timedelta(days=365 / 12 * 6)

cohort['path to exam diff'] = cohort['target pathology date'] - cohort['EXAM_COMPLETED_DATE']

mask_index_cohort = (
    (cohort['path to exam diff'] >= pd.Timedelta(days=0)) &
    (cohort['path to exam diff'] <= six_months)
)

cohort.loc[mask_index_cohort, 'Index'] = 'INDEX'

print(f"✅ Marked {cohort['Index'].eq('INDEX').sum()} rows as 'INDEX'.")

✅ Marked 2549 rows as 'INDEX'.

In [43]:
cohort.reset_index(drop=True, inplace=True)

In [44]:
cohort

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,SIDE,Slab,Series,COMPOSITION_NAME,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,BX_ID,PATHOLOGY_DATE,LESION_CLASS,Index,target pathology date,path to exam diff
0,4330018595,54.0,63737104,2019-08-19,DIAG,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN,None,2020-06-05,291 days
1,4330018595,54.0,63737104,2019-08-19,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN,None,2020-06-05,291 days
2,4330018595,54.0,60103700,2020-06-02,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),"5 - Highly suggestive of malignancy, appropria...",B-Biopsy should be considered,2020-06-02,487690.0,2020-06-05,Malignant,INDEX,2020-06-05,3 days
3,4330018595,54.0,60690108,2020-06-02,SCREEN,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-06-02,NaN,NaT,NaN,INDEX,2020-06-05,3 days
4,4330018595,56.0,452973800,2022-06-09,SCREEN,L,Y,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-06-09,NaN,NaT,NaN,None,2020-06-05,-734 days
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35688,4339945522,45.0,62906727,2019-10-18,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-10-18,NaN,NaT,NaN,None,NaT,NaT
35689,4339945522,48.0,450264459,2022-10-14,DIAG,L,NaN,NaN,Heterogeneously dense (51% - 75%),4A - Suspicious abnormality - biopsy should be...,B-Biopsy should be considered,2022-10-14,353888.0,2022-10-25,High Risk,None,NaT,NaT
35690,4339945522,48.0,450264459,2022-10-14,DIAG,L,Y,DBT,Heterogeneously dense (51% - 75%),4A - Suspicious abnormality - biopsy should be...,B-Biopsy should be considered,2022-10-14,353888.0,2022-10-25,High Risk,None,NaT,NaT
35691,4339945522,48.0,450264459,2022-10-14,DIAG,R,NaN,NaN,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-10-14,NaN,NaT,NaN,None,NaT,NaT
35692,4339945522,48.0,450264459,2022-10-14,DIAG,R,Y,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-10-14,NaN,NaT,NaN,None,NaT,NaT

In [45]:
cancer_patients = set(cohort.loc[
    (cohort['LESION_CLASS'] == 'Malignant'),
    'PATIENT_STUDY_ID'
].unique())

cancer = cohort[cohort['PATIENT_STUDY_ID'].isin(cancer_patients)].copy()
print(f"# of cancer patients: {len(cancer_patients)}")
print(f"cancer rows      : {len(cancer)}")
print(f"Index breakdown:\n{cancer['Index'].value_counts(dropna=False)}")

# of cancer patients: 1112
cancer rows      : 8107
Index breakdown:
Index
None     5558
INDEX    2549
Name: count, dtype: int64

## 2. Locate <span style="color:blue;">**MO cancer**</span> year, "Index" = <span style="color:#00BFFF;">**INDEX-1**</span>. Adjust <span style="color:pink;"> **screening interval (OR search period)**</span> 

Add threshold labeling for the same index time point (threshold ~1.5 months)

#### See [inclusion criteria][ic] to for filtering

[ic]: https://pitt-my.sharepoint.com/:w:/r/personal/trl117_pitt_edu/_layouts/15/doc.aspx?sourcedoc=%7B9c403413-a771-4830-98ab-15171872c4dd%7D&action=edit

In [46]:
cohort = cancer.copy()

In [47]:
# ── Find INDEX-1: exam between 9–18 months before earliest INDEX exam ─────────
min_months     = pd.Timedelta(days=365 / 12 * 0)
max_months = pd.Timedelta(days=365 / 12 * 36)
# ── Sequential labeling with threshold 1.5-month grouping ──────────────────────────────
threshold_group = pd.Timedelta(days=365 / 12 * 1.5)

In [48]:
# 1. Get the earliest INDEX exam date per patient
earliest_index = (
    cohort[cohort['Index'] == 'INDEX']
    .groupby('PATIENT_STUDY_ID')['EXAM_COMPLETED_DATE']
    .min()
    .reset_index()
    .rename(columns={'EXAM_COMPLETED_DATE': 'earliest index date'})
)

cohort = cohort.merge(earliest_index, on='PATIENT_STUDY_ID', how='left')

# 2. Time between each exam and the earliest INDEX exam
cohort['exam to index diff'] = cohort['earliest index date'] - cohort['EXAM_COMPLETED_DATE']

# 3. Window: at least 9 months before, no more than 18 months before
mask_window = (
    (cohort['exam to index diff'] > min_months) &
    (cohort['exam to index diff'] <= max_months) &
    (cohort['Study'] == 'SCREEN')
)

cohort.loc[mask_window, 'Index'] = 'INDEX-1'


# # ── Re-rank: latest exam → INDEX-1, second latest → INDEX-2, etc. ────────────
# # Get unique exam dates per patient within the window
# date_ranks = (
#     cohort[cohort['Index'] == 'INDEX-1']
#     .drop_duplicates(subset=['PATIENT_STUDY_ID', 'EXAM_COMPLETED_DATE'])
#     [['PATIENT_STUDY_ID', 'EXAM_COMPLETED_DATE']]
#     .sort_values(['PATIENT_STUDY_ID', 'EXAM_COMPLETED_DATE'], ascending=[True, False])
# )

# # Rank within each patient: 1 = latest (closest to INDEX), 2 = second latest, ...
# date_ranks['index_rank'] = (
#     date_ranks.groupby('PATIENT_STUDY_ID').cumcount() + 1
# )

# # Merge rank back and overwrite the Index label
# cohort = cohort.merge(
#     date_ranks, on=['PATIENT_STUDY_ID', 'EXAM_COMPLETED_DATE'], how='left'
# )
# ranked_mask = cohort['index_rank'].notna()
# cohort.loc[ranked_mask, 'Index'] = (
#     'INDEX-' + cohort.loc[ranked_mask, 'index_rank'].astype(int).astype(str)
# )
# cohort = cohort.drop(columns='index_rank')




def assign_index_labels(dates):
    dates_sorted = sorted(set(dates), reverse=True)
    labels = {}
    rank = 0
    group_anchor = None
    for d in dates_sorted:
        if group_anchor is None or (group_anchor - d) > threshold_group:
            rank += 1
            group_anchor = d
        labels[d] = f'INDEX-{rank}'
    return labels

window_rows = cohort[mask_window].copy()
date_label_map = {}
for pid, grp in window_rows.groupby('PATIENT_STUDY_ID'):
    mapping = assign_index_labels(grp['EXAM_COMPLETED_DATE'])
    for date, label in mapping.items():
        date_label_map[(pid, date)] = label

cohort.loc[mask_window, 'Index'] = cohort.loc[mask_window].apply(
    lambda row: date_label_map[(row['PATIENT_STUDY_ID'], row['EXAM_COMPLETED_DATE'])],
    axis=1
)


print(f"✅ Marked {cohort['Index'].eq('INDEX-1').sum()} rows as 'INDEX-1'.")
print(f"   Patients with INDEX-1 : {cohort[cohort['Index'] == 'INDEX-1']['PATIENT_STUDY_ID'].nunique()}")
print(f"   Patients with INDEX   : {cohort[cohort['Index'] == 'INDEX']['PATIENT_STUDY_ID'].nunique()}")

✅ Marked 706 rows as 'INDEX-1'.
   Patients with INDEX-1 : 327
   Patients with INDEX   : 1112

In [49]:
cohort = cohort.drop(columns = ["target pathology date", "path to exam diff", "earliest index date", "exam to index diff"])

In [50]:
cohort.head(5)

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,SIDE,Slab,Series,COMPOSITION_NAME,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,BX_ID,PATHOLOGY_DATE,LESION_CLASS,Index
0,4330018595,54.0,63737104,2019-08-19,DIAG,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN,None
1,4330018595,54.0,63737104,2019-08-19,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN,None
2,4330018595,54.0,60103700,2020-06-02,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),"5 - Highly suggestive of malignancy, appropria...",B-Biopsy should be considered,2020-06-02,487690.0,2020-06-05,Malignant,INDEX
3,4330018595,54.0,60690108,2020-06-02,SCREEN,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-06-02,NaN,NaT,NaN,INDEX
4,4330018595,56.0,452973800,2022-06-09,SCREEN,L,Y,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-06-09,NaN,NaT,NaN,None

In [51]:
cohort.head(5)

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,SIDE,Slab,Series,COMPOSITION_NAME,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,BX_ID,PATHOLOGY_DATE,LESION_CLASS,Index
0,4330018595,54.0,63737104,2019-08-19,DIAG,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN,None
1,4330018595,54.0,63737104,2019-08-19,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaT,NaN,None
2,4330018595,54.0,60103700,2020-06-02,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),"5 - Highly suggestive of malignancy, appropria...",B-Biopsy should be considered,2020-06-02,487690.0,2020-06-05,Malignant,INDEX
3,4330018595,54.0,60690108,2020-06-02,SCREEN,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-06-02,NaN,NaT,NaN,INDEX
4,4330018595,56.0,452973800,2022-06-09,SCREEN,L,Y,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-06-09,NaN,NaT,NaN,None

In [52]:
# ── Time-to-INDEX column ──────────────────────────────────────────────────────
# Use the earliest INDEX exam date per patient (the reference anchor)
index_dates = (
    cohort[cohort['Index'] == 'INDEX']
    .groupby('PATIENT_STUDY_ID')['EXAM_COMPLETED_DATE']
    .min()
    .reset_index()
    .rename(columns={'EXAM_COMPLETED_DATE': 'INDEX_DATE'})
)

cohort = cohort.merge(index_dates, on='PATIENT_STUDY_ID', how='left')

is_prior = cohort['Index'].str.match(r'^INDEX-\d+$', na=False)

# Compute days directly — avoids the object-dtype problem
cohort['time_to_INDEX_days'] = (
    cohort['INDEX_DATE'] - cohort['EXAM_COMPLETED_DATE']
).dt.days

# Zero out rows that aren't INDEX-N (set to NaN instead of 0)
cohort.loc[~is_prior, 'time_to_INDEX_days'] = pd.NA

cohort['time_to_INDEX_months'] = (cohort['time_to_INDEX_days'] / 30.5).round(1)

cohort = cohort.drop(columns='INDEX_DATE')

# print(cohort[is_prior][['PATIENT_STUDY_ID','Index','EXAM_COMPLETED_DATE',
#                           'time_to_INDEX_days','time_to_INDEX_months']].head(10))

### <span style="color:#FF6347;">**SAVE**</span> file (cancer_cohort)

In [53]:
cohort["EXAM_COMPLETED_DATE"] = cohort["EXAM_COMPLETED_DATE"].dt.strftime("%Y-%m-%d")
cohort["PATHOLOGY_DATE"] = cohort["PATHOLOGY_DATE"].dt.strftime("%Y-%m-%d")

In [54]:
# output_file = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, 'cancer_cohort' + ".xlsx")
output_file = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, 'cancer_cohort' + ".xlsx")
cohort.to_excel(output_file, index=False)

## **STEP 3**. Extract <span style="color:blue;">**MO cancer**</span> cohort only
### (Output) mo_cancer, mo_cancer_cohort

#### <span style="color:#FF6347;">**READ**</span> file (cancer_cohort)

In [55]:
# output_file = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, 'cancer_cohort_index' + ".xlsx")
output_file = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, 'cancer_cohort' + ".xlsx")
cohort = pd.read_excel(output_file)

In [56]:
cohort

,PATIENT_STUDY_ID,PatientAge,ACCESSION_NUMBER,StudyDate,Study,SIDE,Slab,Series,COMPOSITION_NAME,FINDING_CATEGORY,FINDING_REC,EXAM_COMPLETED_DATE,BX_ID,PATHOLOGY_DATE,LESION_CLASS,Index,time_to_INDEX_days,time_to_INDEX_months
0,4330018595,54,63737104,2019-08-19,DIAG,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaN,NaN,NaN,NaN,NaN
1,4330018595,54,63737104,2019-08-19,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2019-08-19,NaN,NaN,NaN,NaN,NaN,NaN
2,4330018595,54,60103700,2020-06-02,DIAG,R,NaN,DBT,Heterogeneously dense (51% - 75%),"5 - Highly suggestive of malignancy, appropria...",B-Biopsy should be considered,2020-06-02,487690.0,2020-06-05,Malignant,INDEX,NaN,NaN
3,4330018595,54,60690108,2020-06-02,SCREEN,L,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-06-02,NaN,NaN,NaN,INDEX,NaN,NaN
4,4330018595,56,452973800,2022-06-09,SCREEN,L,Y,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-06-09,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8102,4339047841,61,452967718,2022-05-16,SCREEN,R,Y,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2022-05-16,NaN,NaN,NaN,NaN,NaN,NaN
8103,4339077225,47,60400885,2020-03-12,DIAG,L,NaN,NaN,Heterogeneously dense (51% - 75%),"5 - Highly suggestive of malignancy, appropria...",B-Biopsy should be considered,2020-03-12,488857.0,2020-03-19,Malignant,INDEX,NaN,NaN
8104,4339077225,47,60400885,2020-03-12,SCREEN,L,NaN,DBT,Heterogeneously dense (51% - 75%),"5 - Highly suggestive of malignancy, appropria...",B-Biopsy should be considered,2020-03-12,488857.0,2020-03-19,Malignant,INDEX,NaN,NaN
8105,4339077225,47,60400885,2020-03-12,DIAG,R,NaN,NaN,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-03-12,NaN,NaN,NaN,INDEX,NaN,NaN
8106,4339077225,47,60400885,2020-03-12,SCREEN,R,NaN,DBT,Heterogeneously dense (51% - 75%),2 - Benign finding,N-Normal interval follow-up,2020-03-12,NaN,NaN,NaN,INDEX,NaN,NaN

In [57]:
cohort["EXAM_COMPLETED_DATE"] = pd.to_datetime(cohort["EXAM_COMPLETED_DATE"], format="%Y-%m-%d")
cohort["PATHOLOGY_DATE"] = pd.to_datetime(cohort["PATHOLOGY_DATE"], format="%Y-%m-%d")

### **Criteria**:
#### 1. At <span style="color:#8A2BE2;">**INDEX**</span>, "LESION_CLASS" = "Malignant"
##### no need to check as all patients in cancer_cohort already meet this criteria
#### 2. At <span style="color:#00BFFF;">**INDEX-1**</span>, "Series" = "DBT"
#### 3. At <span style="color:#00BFFF;">**INDEX-1**</span>, "FINDING_CATEGORY" = "1 - Negative", "2 - Benign finding"
#### 4. At <span style="color:#00BFFF;">**INDEX-1**</span>, "Study" = "SCREEN"

In [58]:
normal_cats = ['1 - Negative', '2 - Benign finding']

recall_cats = [
    '0 - Need additional imaging evaluation',
    '3 - Probably benign - short interval follow-up',
    '4 - Suspicious abnormality, biopsy should be considered',
    '4A - Suspicious abnormality - biopsy should be considered - low suspicion',
    '4B - Suspicious abnormality - biopsy should be considered - intermediate suspicion',
    '4C - Suspicious abnormality - biopsy should be considered - moderate suspicion',
    '5 - Highly suggestive of malignancy, appropriate action should be taken',
    '6 - Known biopsy proven malignancy'
]

In [59]:
# Patients with ANY recall finding at INDEX-1 (disqualify, takes priority)
recall_patients = set(cohort.loc[
    (cohort['Index'] == 'INDEX-1') &
    (cohort['Series'] == 'DBT') &
    (cohort['FINDING_CATEGORY'].isin(recall_cats)) &
    (cohort['Study'] == 'SCREEN'),
    'PATIENT_STUDY_ID'
].unique())

# Patients with a normal finding at INDEX-1
normal_patients = set(cohort.loc[
    (cohort['Index'] == 'INDEX-1') &
    (cohort['Series'] == 'DBT') &
    (cohort['FINDING_CATEGORY'].isin(normal_cats)) &
    (cohort['Study'] == 'SCREEN'),
    'PATIENT_STUDY_ID'
].unique())

# Exclude wins: remove any patient who appeared in recall
qualifying_patients = normal_patients - recall_patients

print(f"Normal patients     : {len(normal_patients)}")
print(f"Recall patients     : {len(recall_patients)}")
print(f"Overlap removed     : {len(normal_patients & recall_patients)}")
print(f"Qualifying patients : {len(qualifying_patients)}")

mo_cancer = cohort[cohort['PATIENT_STUDY_ID'].isin(qualifying_patients)].copy()
print(f"mo_cancer rows      : {len(mo_cancer)}")
print(f"Index breakdown:\n{mo_cancer['Index'].value_counts(dropna=False)}")

Normal patients     : 254
Recall patients     : 52
Overlap removed     : 1
Qualifying patients : 253
mo_cancer rows      : 2263
Index breakdown:
Index
NaN        906
INDEX      683
INDEX-1    547
INDEX-2    121
INDEX-3      6
Name: count, dtype: int64

In [60]:
mo_cancer_cohort = cohort[cohort['PATIENT_STUDY_ID'].isin(qualifying_patients)].reset_index(drop=True)
mo_cancer_cohort.sort_values(['PATIENT_STUDY_ID', 'StudyDate', 'ACCESSION_NUMBER']).reset_index(drop=True, inplace=True)

mo_cancer_cohort["EXAM_COMPLETED_DATE"] = mo_cancer_cohort["EXAM_COMPLETED_DATE"].dt.strftime("%Y-%m-%d")
mo_cancer_cohort["PATHOLOGY_DATE"] = mo_cancer_cohort["PATHOLOGY_DATE"].dt.strftime("%Y-%m-%d")

##### <span style="color:#FF6347;">**SAVE**</span> **mo_cancer_cohort**

In [61]:
mo_cancer_cohort['PATIENT_STUDY_ID'].nunique()

253

In [62]:
# output_file = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, 'mo_cancer_cohort' + ".xlsx")
output_file = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, 'mo_cancer_cohort' + ".xlsx")

mo_cancer_cohort.to_excel(output_file, index=False)

##### <span style="color:#FF6347;">**SAVE**</span> **mo_cancer** (only retain INDX & INDEX-1)

In [63]:
mo_cancer= mo_cancer_cohort[(mo_cancer_cohort["Index"]=="INDEX") | (mo_cancer_cohort["Index"]=="INDEX-1")]

In [64]:
mo_cancer['PATIENT_STUDY_ID'].nunique()

253

In [65]:
# output_file = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, 'mo_cancer' + ".xlsx")
output_file = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, 'mo_cancer' + ".xlsx")

mo_cancer.to_excel(output_file, index=False)

##### <span style="color:#FF6347;">**SAVE**</span> **mo_cancer_candidate_cohort**

In [66]:
# mo_cancer_candidate_cohort = remaining cancer patients not in mo_cancer_cohort
mo_cancer_pids = set(mo_cancer_cohort['PATIENT_STUDY_ID'].unique())

mo_cancer_candidate_cohort = (
    cohort[~cohort['PATIENT_STUDY_ID'].isin(mo_cancer_pids)]
    .copy()
    .sort_values(['PATIENT_STUDY_ID', 'StudyDate', 'ACCESSION_NUMBER'])
    .reset_index(drop=True)
)

mo_cancer_candidate_cohort["EXAM_COMPLETED_DATE"] = mo_cancer_candidate_cohort["EXAM_COMPLETED_DATE"].dt.strftime("%Y-%m-%d")
mo_cancer_candidate_cohort["PATHOLOGY_DATE"]      = mo_cancer_candidate_cohort["PATHOLOGY_DATE"].dt.strftime("%Y-%m-%d")

print(f"cancer_cohort patients              : {cohort['PATIENT_STUDY_ID'].nunique()}")
print(f"mo_cancer_cohort patients           : {len(mo_cancer_pids)}")
print(f"mo_cancer_candidate_cohort patients : {mo_cancer_candidate_cohort['PATIENT_STUDY_ID'].nunique()}")

cancer_cohort patients              : 1112
mo_cancer_cohort patients           : 253
mo_cancer_candidate_cohort patients : 859

In [67]:
# output_file = os.path.join("P:/Dataset/R01-MO-DBT/MO-DBT-data-curation", study, 'mo_cancer_candidate_cohort' + ".xlsx")
output_file = os.path.join("/Users/tracyliu/Library/CloudStorage/OneDrive-UniversityofPittsburgh/R01-MO-DBT/MO-DBT-data-curation/Data", study, 'mo_cancer_candidate_cohort' + ".xlsx")

mo_cancer_candidate_cohort.to_excel(output_file, index=False)