In [1]:
import pandas as pd
import os
import numpy as np
import re

In [2]:
pd.set_option('display.max_columns', None)

# Data curation

## **STEP 1**. Merge dicomtocsv_series.csv 
### (constructed from the image location, not provided by R3)

### <span style="color:blue">**Main**</span> (determine which part of data)

In [3]:
file_path = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/R3Data"

file_series_r3 = "dicomtocsv_series.csv"

file_series_p1 = "dicomtocsv_series_20250527.xlsx"
file_series_p2 = "dicomtocsv_series_20260803.xlsx"
file_series_p3 = "dicomtocsv_series_20260812.xlsx"
file_series_p4 = "dicomtocsv_series_20260906_p1.xlsx"
file_series_p5 = "dicomtocsv_series_20260906_p2.xlsx"

In [4]:
df_dicom_series_r3 = pd.read_csv(os.path.join(file_path, file_series_r3))

df_dicom_series_p1 = pd.read_excel(os.path.join(file_path, file_series_p1))
df_dicom_series_p2 = pd.read_excel(os.path.join(file_path, file_series_p2))
df_dicom_series_p3 = pd.read_excel(os.path.join(file_path, file_series_p3))
df_dicom_series_p4 = pd.read_excel(os.path.join(file_path, file_series_p4))
df_dicom_series_p5 = pd.read_excel(os.path.join(file_path, file_series_p5))

In [5]:
df_dicom_series_p1.shape, df_dicom_series_p2.shape, df_dicom_series_p3.shape, df_dicom_series_p4.shape, df_dicom_series_p5.shape

((114473, 7), (713, 7), (2423, 7), (11625, 7), (8724, 7))

In [6]:
df_all_series = pd.concat((df_dicom_series_p1, df_dicom_series_p2, df_dicom_series_p3, df_dicom_series_p4, df_dicom_series_p5), axis=0)

df_all_series.shape

(137958, 7)

In [7]:
df_all_series['StudyDate'] = pd.to_datetime(df_all_series['StudyDate'], format='%Y%m%d').dt.strftime('%Y-%m-%d')

In [8]:
df_all_series.head(5)

,PatientID,StudyDate,StudyDescription,AccessionNumber,SeriesNumber,SeriesDescription,FolderPath
0,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,1,Hologic R2 ImageChecker CAD SC,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
1,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R ML,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
2,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R XCCL,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
3,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71300000,L LM C-View,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
4,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71300000,L MLO C-View,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...

In [9]:
df_dicom_series_r3.head(5)

,NumberOfReferences,ImageType,SOPClassUID,StudyDate,AcquisitionDate,AcquisitionDateTime,StudyTime,AccessionNumber,Modality,Manufacturer,StudyDescription,SeriesDescription,ManufacturerModelName,PatientName,PatientID,IssuerOfPatientID,PatientBirthDate,PatientSex,OtherPatientIDs,ScanningSequence,SequenceVariant,ScanOptions,MRAcquisitionType,SequenceName,SliceThickness,MagneticFieldStrength,SpacingBetweenSlices,ProtocolName,Exposure,ConvolutionKernel,MREchoSequence,StudyInstanceUID,SeriesInstanceUID,StudyID,SeriesNumber,InstanceNumber,NumberOfFrames,Rows,Columns,PixelSpacing,BurnedInAnnotation,WindowCenterWidthExplanation,TransferSyntaxUID
0,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,08:39:23,80861023,MG,"HOLOGIC, Inc.",BREAST IMAGING TOMOSYNTHESIS DIAGNOSTIC BILATERAL,L ISO,Selenia Dimensions,NaN,4333469193,NaN,1964-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,NaN,NaN,1.400756,1.882280,1.113140,71100000.0,367.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70
1,1,DERIVED\SECONDARY,1.2.840.10008.5.1.4.1.1.7,2015-01-02,NaN,NaN,11:30:52,81776067,MG,"R2 Technology, Inc.",DIAG MAMMO - DIRECT DIG IMAGE BIL ALL VIEWS,R2 CAD SC,Cenova,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.233100,1.347473,1.119129,1.0,1.0,NaN,1500.0,1250.0,NaN,NaN,NaN,1.2.840.10008.1.2.1
2,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,11:30:52,81776067,MG,"HOLOGIC, Inc.",MAMMOGRAM DIGITAL DX BILAT,L CC,Selenia Dimensions,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,246.0,NaN,NaN,1.233100,1.936507,1.119129,71300000.0,87.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70
3,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,11:30:52,81776067,MG,"HOLOGIC, Inc.",MAMMOGRAM DIGITAL DX BILAT,L MLO,Selenia Dimensions,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250.0,NaN,NaN,1.233100,1.220605,1.119129,71300000.0,93.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70
4,1,DERIVED\PRIMARY,1.2.840.10008.5.1.4.1.1.1.2,2015-01-02,2015-01-02,NaN,11:30:52,81776067,MG,"HOLOGIC, Inc.",MAMMOGRAM DIGITAL DX BILAT,R CC,Selenia Dimensions,NaN,4333843993,NaN,1967-07-01,F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,197.0,NaN,NaN,1.233100,1.340178,1.119129,71300000.0,75.0,NaN,4096.0,3328.0,0.065238\0.065238,NaN,NaN,1.2.840.10008.1.2.4.70

In [10]:
extract_cols = ["PatientID", "AccessionNumber", 
                    "SeriesDescription", "StudyDescription",
                    "Manufacturer", "ManufacturerModelName", 
                    "SliceThickness", "Exposure", 
                    "Rows", "Columns", "PixelSpacing"]

In [11]:
dicom_series_r3_dedup = (
    df_dicom_series_r3[extract_cols]
    .drop_duplicates(
        subset=["PatientID", "AccessionNumber", "SeriesDescription", "StudyDescription"],
        keep='first'
    )
)

In [12]:
df_all = pd.merge(df_all_series, dicom_series_r3_dedup[extract_cols], on=["PatientID", "AccessionNumber", "SeriesDescription", "StudyDescription"], how="left")

In [13]:
df_all_series.shape, df_all.shape

((137958, 7), (137958, 14))

## **STEP 2**. Group by PatientID

### <span style="color:blue">**Main**</span>

In [14]:
df_sort = df_all.sort_values(
        by=['PatientID', 'StudyDate', 'AccessionNumber'],
        ignore_index=True
    )

num_patient = df_sort["PatientID"].nunique()
print(num_patient)

5655

In [15]:
df_sort.head(5)

,PatientID,StudyDate,StudyDescription,AccessionNumber,SeriesNumber,SeriesDescription,FolderPath,Manufacturer,ManufacturerModelName,SliceThickness,Exposure,Rows,Columns,PixelSpacing
0,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,1,Hologic R2 ImageChecker CAD SC,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"R2 Technology, Inc.",Cenova,NaN,NaN,1500.0,1250.0,NaN
1,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R ML,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,102.0,3328.0,2560.0,0.038889\0.038889
2,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R XCCL,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,94.0,3328.0,2560.0,0.038889\0.038889
3,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71300000,L LM C-View,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,71.0,2457.0,1890.0,0.087290\0.087290
4,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71300000,L MLO C-View,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,87.0,2457.0,1890.0,0.086609\0.086609

In [16]:
df_step2 = df_sort.copy()

## **STEP 2.1**. Calculate Age @ Study <span style="color:red"></span>

### <span style="color:darkcyan">**Function**</span>

In [17]:
from pandas import Int64Dtype
def calculate_age_at_study(df):
    """
    Calculates the patient's age in years at the time of the study 
    based on the 'PatientBirthDate' and 'StudyDate' columns.
    """
    
    # 1. Ensure date columns are in datetime format
    # The format 'YYYY-MM-DD' is used for parsing
    try:
        df['BIRTH_DATE_DT'] = pd.to_datetime(df['PatientBirthDate'], format='%Y-%m-%d')
        # Note: The StudyDate column often includes time (e.g., '2020-06-01 09:10:52').
        # We can let pandas infer the format for this one since it's cleaner.
        df['StudyDate_DT'] = pd.to_datetime(df['StudyDate'], errors='coerce') 
    except ValueError as e:
        print(f"Error parsing date format: {e}. Please check your date column formats.")
        return df

    # 2. Calculate the difference in days
    time_difference = df['StudyDate_DT'] - df['BIRTH_DATE_DT']
    
    # 3. Convert the difference into whole years (integer format)
    # The .dt.days attribute gives the number of days, which is divided by 365.25 
    # and then explicitly cast to an integer to capture only the full years elapsed.
    mask = df['BIRTH_DATE_DT'].notna() & df['StudyDate_DT'].notna()
    df.loc[mask, 'PatientAge'] = (time_difference[mask].dt.days / 365.25).astype(int)
    # df['PatientAge'] = (time_difference.dt.days / 365.25).astype('Int64')
    
    # Clean up the intermediate columns
    
    df = df.drop(columns=['BIRTH_DATE_DT', 'StudyDate_DT'])
    
    return df

### <span style="color:blue">**Main**</span>

In [18]:
birth = pd.read_csv(os.path.join(file_path,'dicomtocsv_series.csv')) [["PatientID", "PatientBirthDate"]]

In [19]:
birth = birth.drop_duplicates(subset='PatientID', keep = 'first').reset_index(drop = True)

In [20]:
df_birth = pd.merge(df_sort, birth, on='PatientID', how='left')

In [21]:
df_sort.shape, birth.shape, df_birth.shape

((137958, 14), (5515, 2), (137958, 15))

In [22]:
df_step2 = calculate_age_at_study(df_birth)

In [23]:
df_step2['PatientID'].nunique(), df_step2.loc[df_step2['PatientBirthDate'].notna(), 'PatientID'].nunique(), df_step2.loc[df_step2['PatientBirthDate'].isna(), 'PatientID'].nunique()

(5655, 5515, 140)

In [24]:
df_step2.head(5)

,PatientID,StudyDate,StudyDescription,AccessionNumber,SeriesNumber,SeriesDescription,FolderPath,Manufacturer,ManufacturerModelName,SliceThickness,Exposure,Rows,Columns,PixelSpacing,PatientBirthDate,PatientAge
0,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,1,Hologic R2 ImageChecker CAD SC,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"R2 Technology, Inc.",Cenova,NaN,NaN,1500.0,1250.0,NaN,1965-07-01,54.0
1,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R ML,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,102.0,3328.0,2560.0,0.038889\0.038889,1965-07-01,54.0
2,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R XCCL,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,94.0,3328.0,2560.0,0.038889\0.038889,1965-07-01,54.0
3,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71300000,L LM C-View,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,71.0,2457.0,1890.0,0.087290\0.087290,1965-07-01,54.0
4,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71300000,L MLO C-View,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,87.0,2457.0,1890.0,0.086609\0.086609,1965-07-01,54.0

## **STEP 2.2**. Non-imaging data <span style="color:red">(OPTIONAL, CHECK DISCREPENCY)</span>
### <span style="color:red">  </span>

### <span style="color:blue">**patient_demo**</span>

In [25]:
demo_file_path_cancer = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Cancer/Cleaned/patient_demo.xlsx"
demo_file_path_control = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Control/Cleaned/patient_demo.xlsx"

demo_cancer = pd.read_excel(demo_file_path_cancer)[["PATIENT_STUDY_ID", "BIRTH_DATE"]]
demo_control = pd.read_excel(demo_file_path_control)[["PATIENT_STUDY_ID", "BIRTH_DATE"]]

In [26]:
demo =  pd.concat((demo_cancer, demo_control), axis=0)
demo = demo.drop_duplicates(subset=demo.columns.tolist(), keep = 'first').reset_index(drop = True)

In [27]:
demo.rename(columns={'PATIENT_STUDY_ID': 'PatientID', 'BIRTH_DATE': 'PatientBirthDate'}, inplace=True)

In [28]:
df_birth = pd.merge(df_sort, demo, on='PatientID', how='left')

In [29]:
df_birth['PatientID'].nunique(), df_birth.loc[df_birth['PatientBirthDate'].notna(), 'PatientID'].nunique(), df_birth.loc[df_birth['PatientBirthDate'].isna(), 'PatientID'].nunique()

(5655, 5539, 116)

### <span style="color:blue">**enteredit_findings**</span>

In [30]:
birads_file_path_cancer = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Cancer/Cleaned/enteredit_findings.xlsx"
birads_file_path_control = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Control/Cleaned/enteredit_findings.xlsx"

birads_cancer = pd.read_excel(birads_file_path_cancer)[["PATIENT_STUDY_ID", "ACCESSION_NUMBER", "COMPOSITION_NAME", "FINDING_CATEGORY"]]
birads_control = pd.read_excel(birads_file_path_control)[["PATIENT_STUDY_ID", "ACCESSION_NUMBER", "COMPOSITION_NAME", "FINDING_CATEGORY"]]

In [31]:
birads =  pd.concat((birads_cancer, birads_control), axis=0)
# birads =  birads_cancer.copy()
birads = birads.drop_duplicates(subset=birads.columns.tolist(), keep = 'first').reset_index(drop = True)

In [32]:
birads.rename(columns={'PATIENT_STUDY_ID': 'PatientID', 'ACCESSION_NUMBER': 'AccessionNumber'}, inplace=True)

In [33]:
df_birads = pd.merge(df_sort, birads, on=['PatientID', 'AccessionNumber'], how='left')

In [34]:
df_birads.columns

Index(['PatientID', 'StudyDate', 'StudyDescription', 'AccessionNumber',
       'SeriesNumber', 'SeriesDescription', 'FolderPath', 'Manufacturer',
       'ManufacturerModelName', 'SliceThickness', 'Exposure', 'Rows',
       'Columns', 'PixelSpacing', 'COMPOSITION_NAME', 'FINDING_CATEGORY'],
      dtype='object')

In [35]:
df_birads['PatientID'].nunique(), df_birads.loc[df_birads['FINDING_CATEGORY'].notna(), 'PatientID'].nunique(), df_birads.loc[df_birads['FINDING_CATEGORY'].isna(), 'PatientID'].nunique()

(5655, 5536, 119)

### <span style="color:blue">**risk_factors**</span>

In [36]:
risk_file_path_cancer = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Cancer/Cleaned/risk_factors.xlsx"
risk_file_path_control = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Control/Cleaned/risk_factors.xlsx"

risk_cancer = pd.read_excel(birads_file_path_cancer)[["PATIENT_STUDY_ID", "ACCESSION_NUMBER"]]
risk_control = pd.read_excel(birads_file_path_control)[["PATIENT_STUDY_ID", "ACCESSION_NUMBER"]]

In [37]:
risk =  pd.concat((risk_cancer, risk_control), axis=0)
# risk =  risk_cancer.copy()
risk = risk.drop_duplicates(subset=risk.columns.tolist(), keep = 'first').reset_index(drop = True)
risk['Risk'] = 1

In [38]:
risk.rename(columns={'PATIENT_STUDY_ID': 'PatientID', 'ACCESSION_NUMBER': 'AccessionNumber'}, inplace=True)

In [39]:
df_risk = pd.merge(df_sort, risk, on=['PatientID', 'AccessionNumber'], how='left')

In [40]:
df_risk.columns

Index(['PatientID', 'StudyDate', 'StudyDescription', 'AccessionNumber',
       'SeriesNumber', 'SeriesDescription', 'FolderPath', 'Manufacturer',
       'ManufacturerModelName', 'SliceThickness', 'Exposure', 'Rows',
       'Columns', 'PixelSpacing', 'Risk'],
      dtype='object')

In [41]:
df_risk['PatientID'].nunique(), df_risk.loc[df_risk['Risk'].notna(), 'PatientID'].nunique(), df_risk.loc[df_risk['Risk'].isna(), 'PatientID'].nunique()

(5655, 5536, 119)

### <span style="color:blue">**vitals**</span>

In [42]:
vital_file_path_cancer = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Cancer/Cleaned/vitals.xlsx"
vital_file_path_control = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Control/Cleaned/vitals.xlsx"

vital_cancer = pd.read_excel(vital_file_path_cancer)[["PATIENT_STUDY_ID"]]
vital_control = pd.read_excel(vital_file_path_control)[["PATIENT_STUDY_ID"]]

In [43]:
vital =  pd.concat((vital_cancer, vital_control), axis=0)
# vital =  vital_cancer.copy()
vital = vital.drop_duplicates(subset=vital.columns.tolist(), keep = 'first').reset_index(drop = True)
vital['vital'] = 1

In [44]:
vital.rename(columns={'PATIENT_STUDY_ID': 'PatientID'}, inplace=True)

In [45]:
df_vital = pd.merge(df_sort, vital, on=['PatientID'], how='left')

In [46]:
df_vital.columns

Index(['PatientID', 'StudyDate', 'StudyDescription', 'AccessionNumber',
       'SeriesNumber', 'SeriesDescription', 'FolderPath', 'Manufacturer',
       'ManufacturerModelName', 'SliceThickness', 'Exposure', 'Rows',
       'Columns', 'PixelSpacing', 'vital'],
      dtype='object')

In [47]:
df_vital['PatientID'].nunique(), df_vital.loc[df_vital['vital'].notna(), 'PatientID'].nunique(), df_vital.loc[df_vital['vital'].isna(), 'PatientID'].nunique()

(5655, 5411, 244)

### <span style="color:blue">**procedure_notes**</span>

In [48]:
procedure_notes_file_path_cancer = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation/Cancer/Cleaned/procedure_notes.xlsx"

procedure_notes_cancer = pd.read_excel(procedure_notes_file_path_cancer)[["PATIENT_STUDY_ID"]]

In [49]:
procedure_notes =  procedure_notes_cancer.copy()
procedure_notes = procedure_notes.drop_duplicates(subset=procedure_notes.columns.tolist(), keep = 'first').reset_index(drop = True)
procedure_notes['procedure_notes'] = 1

In [50]:
procedure_notes.rename(columns={'PATIENT_STUDY_ID': 'PatientID'}, inplace=True)

In [51]:
df_procedure_notes = pd.merge(df_sort, procedure_notes, on=['PatientID'], how='left')

In [52]:
df_procedure_notes.columns

Index(['PatientID', 'StudyDate', 'StudyDescription', 'AccessionNumber',
       'SeriesNumber', 'SeriesDescription', 'FolderPath', 'Manufacturer',
       'ManufacturerModelName', 'SliceThickness', 'Exposure', 'Rows',
       'Columns', 'PixelSpacing', 'procedure_notes'],
      dtype='object')

In [53]:
df_procedure_notes['PatientID'].nunique(), df_procedure_notes.loc[df_procedure_notes['procedure_notes'].notna(), 'PatientID'].nunique(), df_procedure_notes.loc[df_procedure_notes['procedure_notes'].isna(), 'PatientID'].nunique()

(5655, 766, 4889)

## **STEP 3.** Add tags (Study, Side, Series)

In [54]:
dicom = df_step2

In [55]:
dicom.head(3)

,PatientID,StudyDate,StudyDescription,AccessionNumber,SeriesNumber,SeriesDescription,FolderPath,Manufacturer,ManufacturerModelName,SliceThickness,Exposure,Rows,Columns,PixelSpacing,PatientBirthDate,PatientAge
0,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,1,Hologic R2 ImageChecker CAD SC,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"R2 Technology, Inc.",Cenova,NaN,NaN,1500.0,1250.0,NaN,1965-07-01,54.0
1,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R ML,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,102.0,3328.0,2560.0,0.038889\0.038889,1965-07-01,54.0
2,4330018595,2019-08-19,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,63737104,71100000,R XCCL,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...,"HOLOGIC, Inc.",Selenia Dimensions,NaN,94.0,3328.0,2560.0,0.038889\0.038889,1965-07-01,54.0

In [56]:
dicom_copy = dicom.copy()

### <span style="color:blue"> **Study**</span> (SCREEN, DIAG)

In [57]:
study_types = {
    "DIAG":   ["DIAG", "DIAGNOSTIC", "DX"],
    "SCREEN": ["SCREENING", "SCREEN"],
}

In [58]:
column_to_check = 'StudyDescription'
type_column = 'Study'

dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

for label, terms in study_types.items():
    pattern = '|'.join(re.escape(t) for t in terms)
    mask = dicom_copy[column_to_check].str.contains(pattern, case=False, na=False, regex=True)
    dicom_copy.loc[mask, type_column] = label

### <span style="color:blue">**Side**</span> (R, L)

In [59]:
side_types = {
    "R": ["RIGHT", "RT", "R XCCL", "R MLO", "R CC", "R ML", "R SIO", "R LM"],
    "L": ["LEFT", "LT", "L XCCL", "L MLO", "L CC", "L ML", "L SIO", "L LM"],
}

In [60]:
column_to_check = 'SeriesDescription'
type_column = 'Side'

dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

for label, terms in side_types.items():
    pattern = '|'.join(re.escape(t) for t in terms)
    mask = dicom_copy[column_to_check].str.contains(pattern, case=False, na=False, regex=True)
    dicom_copy.loc[mask, type_column] = label

### <span style="color:blue">**Series**</span> (DBT, IN2D, C VIEW, SECURE)

In [61]:
series_types = {
    "DBT":    ["Breast Tomosynthesis"],
    "IN2D":   ["Intelligent 2D"],
    "C VIEW": ["C-View"],
    "SECURE": ["SecurView", "CAD SC"],
}

ffdm_exact = ["R CC", "R MLO", "R ML", "L CC", "L MLO", "L ML",
              "L XCCL", "R XCCL", "R LM", "L LM",
              "R SIO", "L SIO", "RT", "LT"
              ]

In [62]:
column_to_check = 'SeriesDescription'
type_column = 'Series'

dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

for label, terms in series_types.items():
    pattern = '|'.join(re.escape(t) for t in terms)
    mask = dicom_copy[column_to_check].str.contains(pattern, case=False, na=False, regex=True)
    dicom_copy.loc[mask, type_column] = label

# Exact matches for FFDM
ffdm_mask = dicom_copy[column_to_check].str.strip().str.upper().isin(
    [t.upper() for t in ffdm_exact]
)
dicom_copy.loc[ffdm_mask, type_column] = "FFDM"

### <span style="color:blue">**View**</span> (MLO, CC)

In [63]:
view_types = {

    "CC":  ["L CC", "R CC"],
    "ML":  ["L ML", "R ML"],
    "XCCL":  ["L XCCL", "R XCCL"],
    "LM":  ["L LM", "R LM"],
    "MLO": ["L MLO", "R MLO"],
    "SIO": ["R SIO", "L SIO"],
}

In [64]:
column_to_check = 'SeriesDescription'
type_column = 'View'

dicom_copy[column_to_check] = dicom_copy[column_to_check].astype(str)

for label, terms in view_types.items():
    pattern = '|'.join(re.escape(t) for t in terms)
    mask = dicom_copy[column_to_check].str.contains(pattern, case=False, na=False, regex=True)
    dicom_copy.loc[mask, type_column] = label

### <span style="color:blue">**Reorder columns**</span>

In [65]:
dicom_copy.columns

Index(['PatientID', 'StudyDate', 'StudyDescription', 'AccessionNumber',
       'SeriesNumber', 'SeriesDescription', 'FolderPath', 'Manufacturer',
       'ManufacturerModelName', 'SliceThickness', 'Exposure', 'Rows',
       'Columns', 'PixelSpacing', 'PatientBirthDate', 'PatientAge', 'Study',
       'Side', 'Series', 'View'],
      dtype='object')

In [66]:
extract_cols = [
                    "Manufacturer", "ManufacturerModelName", 
                    "SliceThickness", "Exposure", 
                    "Rows", "Columns", "PixelSpacing"]

In [67]:
# dicom_copy = dicom_copy[['PatientID', 
#         'AccessionNumber', 'Study', 'Side', 'Series', 'View',    
#         'StudyDate', 'StudyDescription',
#         'SeriesDescription', 'SeriesNumber', 
#         'FolderPath'
#         ]]

dicom_copy = dicom_copy[['PatientID', 'PatientBirthDate', 'PatientAge',
        'AccessionNumber', 'StudyDate',
        'Study', 'Side', 'Series', 'View',    
        'StudyDescription',
        'SeriesDescription', 'SeriesNumber', 
        "Manufacturer", "ManufacturerModelName", 
        "SliceThickness", "Exposure", 
        "Rows", "Columns", "PixelSpacing",
        'FolderPath'
        ]]

In [68]:
dicom_copy.head(3)

,PatientID,PatientBirthDate,PatientAge,AccessionNumber,StudyDate,Study,Side,Series,View,StudyDescription,SeriesDescription,SeriesNumber,Manufacturer,ManufacturerModelName,SliceThickness,Exposure,Rows,Columns,PixelSpacing,FolderPath
0,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,NaN,SECURE,NaN,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,Hologic R2 ImageChecker CAD SC,1,"R2 Technology, Inc.",Cenova,NaN,NaN,1500.0,1250.0,NaN,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
1,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,R,FFDM,ML,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R ML,71100000,"HOLOGIC, Inc.",Selenia Dimensions,NaN,102.0,3328.0,2560.0,0.038889\0.038889,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
2,4330018595,1965-07-01,54.0,63737104,2019-08-19,DIAG,R,FFDM,XCCL,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R XCCL,71100000,"HOLOGIC, Inc.",Selenia Dimensions,NaN,94.0,3328.0,2560.0,0.038889\0.038889,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...

### <span style="color:#FF6347;">**SAVE**</span> file

In [69]:
path = "P:/Dataset/R01-MO-DBT/MO-DBT-data-curation"

In [70]:
output_file = os.path.join(path,'dicom_tag' + ".xlsx")
dicom_copy.to_excel(output_file, index=False)

### <span style="color:#FF6347;">**READ**</span> file

In [71]:
file_path = os.path.join(path,'dicom_tag' + ".xlsx")
dicom = pd.read_excel(file_path)

In [72]:
dicom[dicom["Series"]=="DBT"]

,PatientID,PatientBirthDate,PatientAge,AccessionNumber,StudyDate,Study,Side,Series,View,StudyDescription,SeriesDescription,SeriesNumber,Manufacturer,ManufacturerModelName,SliceThickness,Exposure,Rows,Columns,PixelSpacing,FolderPath
39,4330066079,1989-07-01,30.0,61259016,2020-01-14,DIAG,L,DBT,CC,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,L CC Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1890.0,0.088364\0.088364,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
40,4330066079,1989-07-01,30.0,61259016,2020-01-14,DIAG,L,DBT,MLO,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,L MLO Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1890.0,0.088500\0.088500,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
41,4330066079,1989-07-01,30.0,61259016,2020-01-14,DIAG,R,DBT,CC,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R CC Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1890.0,0.088500\0.088500,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
42,4330066079,1989-07-01,30.0,61259016,2020-01-14,DIAG,R,DBT,MLO,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R MLO Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1890.0,0.088500\0.088500,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
75,4330116791,1963-07-01,56.0,61499674,2019-12-17,DIAG,L,DBT,CC,DIAG DIG MAMMO LEFT ALL VIEWS WITH TOMOSYNTHESIS,L CC Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1996.0,0.106407\0.106407,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137766,4339601084,1972-07-01,46.0,77038224,2018-11-07,DIAG,L,DBT,MLO,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,L MLO Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1996.0,0.106192\0.106192,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
137767,4339601084,1972-07-01,46.0,77038224,2018-11-07,DIAG,R,DBT,CC,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R CC Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1996.0,0.107029\0.107029,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
137768,4339601084,1972-07-01,46.0,77038224,2018-11-07,DIAG,R,DBT,MLO,DIAG DIG MAMMO BILAT ALL VIEWS WITH TOMOSYNTHESIS,R MLO Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1996.0,0.106860\0.106860,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
137775,4339601084,1972-07-01,46.0,65758752,2019-05-16,DIAG,R,DBT,CC,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,R CC Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1996.0,0.106843\0.106843,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...
137776,4339601084,1972-07-01,46.0,65758752,2019-05-16,DIAG,R,DBT,MLO,DIAG DIG MAMMO RIGHT ALL VIEWS WITH TOMOSYNTHESIS,R MLO Breast Tomosynthesis Image,73200000,"HOLOGIC, Inc.",Selenia Dimensions,1.0,NaN,2457.0,1996.0,0.107180\0.107180,J:\Testing\jlee\MO_DBT\DICOM_data_and_summarie...

In [73]:
dicom[dicom["Series"]=="DBT"]["PatientID"].unique().size

2323

In [74]:
file_path = os.path.join(path,'R3Data/dicomtocsv_series' + ".csv")
dicom_series = pd.read_csv(file_path)

file_path = os.path.join(path,'R3Data/dicomtocsv_study' + ".csv")
dicom_study = pd.read_csv(file_path)

In [75]:
pids_dicom_plus_series = set(dicom_series['PatientID'].unique())
pids_dicom_plus_study = set(dicom_study['PatientID'].unique())
pids_dicom = set(dicom['PatientID'].unique())

In [76]:
print("Number of patients we have image available: ", len(pids_dicom), 
"\nNumber of patients in R3 series and study: ", len(pids_dicom_plus_series), 
"\nDiscrpency between R3 series vs R3 study: ", len(pids_dicom_plus_series - pids_dicom_plus_study), 
"\nNumber of patients that we don't have corresponding R3 series: ", len(pids_dicom - pids_dicom_plus_series), 
"\nNumber of patients that we don't have corresponding R3 study: ", len(pids_dicom - pids_dicom_plus_study))

Number of patients we have image available:  5655
Number of patients in R3 series and study:  5515
Discrpency between R3 series vs R3 study:  0
Number of patients that we don't have corresponding R3 series:  140
Number of patients that we don't have corresponding R3 study:  140